2024-01-09 15:04:49.229970: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-09 15:04:49.513879: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-09 15:04:49.513927: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-01-09 15:04:53.684812: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-09 15:04:53.686762: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-09 15:04:53.686781: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/cluster/apps/nss/python/3.7.4/x86_64/lib64/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Traceback (most recent call last):
  File "glycomics_iterative.py", line 71, in <module>
    main()
  File "glycomics_iterative.py", line 36, in main
    full, train_datasets, test, n_markers_dict = load_and_split_data(TECHS, OUTDIR, LABEL, LABEL_2)
  File "/cluster/home/hugifl/scim/utils_training.py", line 32, in load_and_split_data
    data = anndata.read(path)
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 224, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/cluster/scratch/hugifl/glycomics_only_gex_no_scaling/lectin.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
