2024-01-03 15:07:25.942637: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-03 15:07:26.334407: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-03 15:07:26.334458: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-01-03 15:07:30.196633: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-03 15:07:30.198639: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:/cluster/apps/gcc-4.8.5/r-4.1.3-zhohf2ta256vpv74j4uq24doqdfqyllj/rlib/R/lib:/cluster/apps/gcc-4.8.5/zlib-1.2.9-dfllxkobdix3ujpfjwsnnyv6vj7ufwcw/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.20-ut6yhgxs5opzdjsqbfm7kaodfpqj7haf/lib:/cluster/apps/nss/python/3.7.4/x86_64/lib64:/cluster/apps/gcc-4.8.5/hdf5-1.10.9-j3urjulfpkxdslamrubc4p4ssfv5g5iu/lib:/cluster/apps/gcc-4.8.5/fastqc-0.11.9-idl77akhjkw5ounkpxxur2vg74aigeep/lib:/cluster/apps/gcc-4.8.5/emboss-6.6.0-j6uwtc5qzuwmm37w4fetov5n4wabfskd/lib:/cluster/apps/gcc-4.8.5/boost-1.74.0-pyomvleapuufbg4siz7g3jwtkkvwfudc/lib:/cluster/apps/gcc-4.8.5/perl-5.34.0-75yvrlt7bfvt76rc7r2oh245oic3idvg/lib:/cluster/home/hugifl/resources/software/lib:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib::
2024-01-03 15:07:30.198658: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2024-01-03 15:07:39.231156: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-01-03 15:07:39.231481: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (eu-a2p-192): /proc/driver/nvidia/version does not exist
2024-01-03 15:07:39.234460: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/cluster/apps/nss/python/3.7.4/x86_64/lib64/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/cluster/home/hugifl/.local/lib/python3.7/site-packages/keras/backend.py:452: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  "`tf.keras.backend.set_learning_phase` is deprecated and "
number of genes:  41
Initializing latent space by training VAE
Epoch 0
Traceback (most recent call last):
  File "scRNA_cytof.py", line 379, in <module>
    main()
  File "scRNA_cytof.py", line 339, in main
    disc_loss, _ = trainer.discriminator_step(source, target, data, prior, dlabel, plabel)
  File "/cluster/home/hugifl/scim/scim/trainer.py", line 95, in discriminator_step
    _, pcodes, _ = self.vae_lut[ptech].forward(prior)
  File "/cluster/home/hugifl/scim/scim/model.py", line 30, in forward
    mu, logvar = self.encode(inputs)
  File "/cluster/home/hugifl/scim/scim/model.py", line 18, in encode
    logits = self.encoder_net(inputs)
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/cluster/home/hugifl/.local/lib/python3.7/site-packages/keras/engine/input_spec.py", line 296, in assert_input_compatibility
    f'Input {input_index} of layer "{layer_name}" is '
ValueError: Input 0 of layer "scrna-encoder" is incompatible with the layer: expected shape=(None, 41), found shape=(256, 256)
